[package]
name = "murmur-ice-rust-experiments"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = { version = "1.0.130", features = ["c++20", "c++14", "c++17"] }
[build-dependencies]
cxx-build = "1.0.130"
